# DEVELOPMENT
version: '3'
services:
  postgres-db:
    build:
      dockerfile: Dockerfile
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5410:5432'
    shm_size: 1g
  mysql-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ${MY_SQL_DB_NAME}
      MYSQL_USER: ${MY_SQL_DB_USERNAME}
      MYSQL_PASSWORD: ${MY_SQL_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MY_SQL_DB_PASSWORD}
    ports:
      - '5409:3306'
    expose:
      - '5409'
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "werwerWER1"
    ports:
      - 1433:1433
  oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracledatabase    
    ports:    
      - 1521:1521
    environment:
      ORACLE_PWD: root
  mariadb:
    image: mariadb:11.4-ubi
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIA_DB_PASSWORD}
      MARIADB_PASSWORD: ${MARIA_DB_PASSWORD}
      MARIADB_USER: ${MARIA_DB_USERNAME}
      MARIADB_DATABASE: ${MARIA_DB_NAME}
    ports:
      - "3306:3306"
  redis:
    image: redis:latest
    container_name: db_study_redis
    ports:
      - "6379:6379"
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
